services:
  nginx:
    container_name: docker-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-nginx/html:/usr/share/nginx/html
      - ./docker-nginx/configs:/etc/nginx/conf.d
      - ./docker-nginx/certs:/etc/letsencrypt
      - ./:/logs
    image: nginx
  mongo:
    image: mongo:4.2.5
