services:
  nginx:
    image: nginx
    container_name: docker-nginx
    ports:
      - "80:80"
    volumes:
      - ~/docker-nginx/html:/usr/share/nginx/html
      - ~/docker-nginx/default.conf:/etc/nginx/conf.d/default.conf