services:
  nginx:
    image: nginx
    container_name: docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker-nginx/html:/usr/share/nginx/html:ro
      - ./docker-nginx/config-http-only/default.conf:/etc/nginx/conf.d/default.conf:ro
    #network_mode: bridge
